export  const amenities = [
    { id: 'amenity_wifi', label: 'Wifi', value: 'Wifi' },
    { id: 'amenity_kitchen', label: 'Full kitchen', value: 'Full kitchen' },
    { id: 'amenity_washer_dryer', label: 'Washer & Dryer', value: 'Washer & Dryer' },
    { id: 'amenity_free_parking', label: 'Free Parking', value: 'Free Parking' },
    { id: 'amenity_pool', label: 'Swimming Pool', value: 'Swimming Pool' },
    { id: 'amenity_hot_tub', label: 'Hot Tub', value: 'Hot Tub' },
    { id: 'amenity_24_7_security', label: '24/7 Security', value: '24/7 Security' },
    { id: 'amenity_wheelchair_accessible', label: 'Wheelchair Accessible', value: 'Wheelchair Accessible' },
    { id: 'amenity_elevator_access', label: 'Elevator Access', value: 'Elevator Access' },
    { id: 'amenity_dishwasher', label: 'Dishwasher', value: 'Dishwasher' },
    { id: 'amenity_gym_fitness_center', label: 'Gym/Fitness Center', value: 'Gym/Fitness Center' },
    { id: 'amenity_air_conditioning', label: 'Air Conditioning', value: 'Air Conditioning' },
    { id: 'amenity_balcony_patio', label: 'Balcony/Patio', value: 'Balcony/Patio' },
    { id: 'amenity_smart_tv', label: 'Smart TV', value: 'Smart TV' },
    { id: 'amenity_coffee_maker', label: 'Coffee Maker', value: 'Coffee Maker' },
  ];